### ISSUE TITLE
Consider collaborating with Fluffy?

### ISSUE THREAD

**Issue by raamsri** [SSStormy/lightfswatcher#1]
Hey!

It appears to me that you are shooting for a cross platform file system watcher. Great!
I have written a inotify library [tinkershack/fluffy](https://github.com/tinkershack/fluffy) that might interest you. Please have a look?

Sorry about the unseemly 'issue'. Couldn't find other means to reach out.

**Comment by justas-d** [comment]
Sorry, uninterested.
